# Generated by Django 2.0.4 on 2021-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticmetric',
            old_name='time',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='statisticmetric',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='riskevent',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否是有效告警规则'),
        ),
    ]
