# Generated by Django 2.0.4 on 2021-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20210226_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskevent',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='rule',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否是有效告警规则'),
        ),
    ]
