# Generated by Django 2.0.4 on 2021-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_statisticmetric_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticmetric',
            name='std',
            field=models.CharField(max_length=256, null=True, verbose_name='std'),
        ),
    ]
